### ISSUE TITLE
Can burgomaster help test the phar

### ISSUE THREAD

**Issue by lsolesen** [mtdowling/Burgomaster#4]
How can one automatically test whether the .phar works as expected?

**Comment by mtdowling** [comment]
No I don't think Burgomaster would help directly with that. All it does is build the phar you configured. You could update your tests to work off of the phar rather than the classes in your repository. That's something I've done in the past.

**Comment by lsolesen** [comment]
Do you have an open source example on that?

**Comment by mtdowling** [comment]
Not anything that easily comprehensible, but I think that's what the AWS SDK for PHP does. You could try to figure out how it works by starting at the Makefile: https://github.com/aws/aws-sdk-php/blob/master/Makefile#L33
