### ISSUE TITLE
Invalid constant name in the stub

### ISSUE THREAD

**Issue by codemedic** [mtdowling/Burgomaster#5]
It seems that the constant name generated in the stub is slightly wrong.

```
<?php
define('ALIAS.PHAR_PHAR', true);
Phar::mapPhar('alias.phar');
require 'phar://alias.phar/autoloader.php';
```

As you can see, `.PHAR` in `ALIAS.PHAR_PHAR` is not ideal.
It will be a minor fix to the logic that is already in there to get rid of that.

**Comment by mtdowling** [comment]
Thanks. Merged.
